name: one_day_keizai
version: '${project.version}'
main: lobby.one_day_keizai.One_day_keizai
api-version: '1.20'
depend: [Vault]
softdepend: [Multiverse-Core]

commands:
  debt:
    description: 債権管理コマンド
    usage: /debt <lend|repay|forgive|list> [player] [amount] [minutes]
  bal:
    description: 残高確認
    usage: /bal
  auction:
    description: オークション入札
    usage: /auction <金額>
  ow:
    description: オーバーワールド移動
    usage: /ow <enter|return>
