name: one_day_keizai
version: '${project.version}'
main: lobby.one_day_keizai.One_day_keizai
api-version: '1.20'
depend: [Vault, Multiverse-Core]

commands:
  debt:
    description: 債権管理コマンド
    usage: /debt <lend|repay|forgive|list> [player] [amount] [minutes]
  bal:
    description: 残高確認
    usage: /bal
  auction:
    description: オークション入札・管理
    usage: /auction <金額|list|reload>
  ow:
    description: オーバーワールド移動
    usage: /ow <enter|return>
    permission: one_day_keizai.ow
    permission-message: §cこのコマンドは権限持ちのみ使用できます。
  job:
    description: 職業管理
    usage: /job <select|info|list> [職業名]

permissions:
  one_day_keizai.ow:
    description: /ow コマンドの使用権限
    default: op
